export const API_ENDPOINTS = {
  USERS_LOGIN: '/gitlab/oauth/token',
  USERS_ME: '/user/getuserprofile',
  USERS_GETALL: '/user/userlist',
  EMPLOYEE_GETALL: '/employee/employeelist',
  EMPLOYEE_GETBYCODE: '/employee/employeebycode',
  EMPLOYEE_BYUSERNAME: '/employee/employeebyusername',
  BLOCK_EMPLOYEE: '/employee/updatestatus',
  meEndpoint: '/user/getuserprofile',
  loginEndpoint: '/jwt/login',
  registerEndpoint: '/jwt/register',
  storageTokenKeyName: 'accessToken',
  onTokenExpiration: 'refreshToken', // logout | refreshToken
  GITLAB_ALLPROJECT: '/gitlab/getallproject',
  POST_EMPLOYEE: '/employee/postemployee',
  APPROVE_EMPLOYEE: '/employee/updatestatus',
  CANDIDATE: '/data/getlistcandidate',
  CANDIDATE_GETBYCODE: '/data/getresultcandidate',
  CANDIDATPOST: '/data/createcandidate',
  CANDIDATEACCESS: '/data/candidatelogin',
  CANDIDATEQUESTION: '/data/getsetofquestion',
  CANDIDATESUBMIT: '/data/submittestanswer',
  BLOG_GETALL: '/data/allblog',
  EMPLOYEE_GETBYTEAMCODE: '/employee/employeelistbyteamcd',
  EMPLOYEE_SUBMITAPPFORLEAVE: '/employee/postapplicationforleave',
  EMPLOYEE_APPROVE_APPLICATION_FOR_LEAVE: '/employee/getlistapplicationforleave',
  EMPLOYEE_APPLICATION_FOR_LEAVE_BYID: '/employee/getapplicationforleavebyid',
  EMPLOYEE_APPROVE_FOR_LEAVE: '/employee/approvedapplicationforleave',
  EMPLOYEE_REJECT_FOR_LEAVE: '/employee/rejectapplicationforleave',
  EMPLOYEE_CONFIRM_FOR_LEAVE: '/employee/confirmapplicationforleave',
  GET_MENU: '/employee/getmenu',
  GET_EMPLOYEE_LISTFL: '/employee/getlistafl',
  UPDATE_EMPLOYEE_INFO: '/employee/updateemployeeinfor',
  DEVICE_GETALL: '/employee/getalldevice',
  SUBMIT_ONSIE: '/employee/registeronsite'
}
